### ISSUE TITLE
Wallet backup button

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mojo-java-wallet#1]
A dedicated wallet backup button in either a dropdown or on the wallet main screen would be extremely helpful, especially for new users who don't know how to navigate within the files for their actually wallet file. This feature should allow the user to decide where to save the backup, whether it should include the secret, and whether or not they want to password protect their backup.

**Comment by Stoner19** [comment]
Might be worth considering adding this "backup" button the the popup that is shown when a new wallet is created

**Comment by 0rtis** [comment]
We changed the wording in the next version. It will explicitly mention to copy the *mcm* file in a safe place
