### ISSUE TITLE
Request: no need to import tag and wallet address to send the transaction

### ISSUE THREAD

**Issue by angryolk** [mochimodev/mojo-java-wallet#12]
Is it possible that you do not need to import the Tag or address to send the transaction?

**Comment by 0rtis** [comment]
At the moment, it is preferable to keep a record of all addresses used in Mojo. We might allow transaction to unrecorded address once the wallet is mature enough.

**Comment by 0rtis** [comment]
Had a change of heart and decided to implement this, since it is a standard feature in other crypto wallet.
Will be available on the next release.
