### ISSUE TITLE
Request: automatically resolve the tag when importing tag 

### ISSUE THREAD

**Issue by angryolk** [mochimodev/mojo-java-wallet#13]
isn't it an unnecessary step that when you input a tag then you need to press the "resolve the tag" button? can it automatically resolve everytime you input a tag?

also at Import section, Name change to - > Name(optional) would be better.

**Comment by 0rtis** [comment]
This is a valid point. I will try to include it in the next release.

**Comment by 0rtis** [comment]
Done. Will be on the next version of Mojo.
