### ISSUE TITLE
Transactions tab

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mojo-java-wallet#3]
I don't know if this is possible with the current code, but it would be extremely helpful to add a "transactions" tab on the main screen along with the other existing ones so that users can view what transactions within their addresses/wallets.

Or, maybe make the transactions visible after double clicking the address you want to view. It would be helpful if they reflected a send from another tag/address or a block solved.

**Comment by 0rtis** [comment]
Mojo does not have a copy of the blockchain to display transaction history. At best, it should be possible to show the history of the user's "actions" like sending, create tag, etc. But actions does not always translate into actual operation on the blockchain (transaction rejected, orphan chain) so it might confuse the user.

**Comment by angryolk** [comment]
but isn't it a transaction history and point it out to the explorer is a standard practice in the blockchain?

**Comment by 0rtis** [comment]
Transactions are indeed recorded in the blockchain but Mojo doesnt hold a copy of the blockchain. The next version of Mojo will display `transaction id` to make it easier to search a specific transaction in the block explorer

**Comment by 0rtis** [comment]
As stated, Mojo is a lightweight wallet that does not sync a local copy of the blockchain. Therefore, there is no "clean" way of tracking transactions .
