### ISSUE TITLE
Hide the "delete" button

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mojo-java-wallet#4]
The "Delete" button right on the addresses popup when double clicking creates too much room for error. I'd recommend this be hidden somewhere, or maybe create a dropdown that enables "Dev tools" where its then enabled.

I know when a user clicks the button there is a popup asking if they're sure they want to delete it, but in my experience I find that the option to delete an address is never a good thing.

<img width="748" alt="screen shot 2019-03-03 at 10 13 42 am" src="https://user-images.githubusercontent.com/8030643/53700210-3afff400-3dad-11e9-9ea9-3b2646ae6788.png">

**Comment by 0rtis** [comment]
The wallet actually never 'delete' anything. The address is just flagged as 'Deleted' and can be restored. Next version will use the wording `Archive` to avoid confusion.
