### ISSUE TITLE
"Roll source address" can be confusing

### ISSUE THREAD

**Issue by Stoner19** [mochimodev/mojo-java-wallet#5]
I'm simply proposing a change to the way this is read. As it is `Roll source address` isn't very intuitive to an unexperienced user. The wiki states:
```
By default, the wallet will automatically activate a new address from the pool as the change address of the transaction. You can specify a change address by unticking the checkbox Roll source address
```
While this makes sense to me, I think the verbiage should just be change in the wallet itself to make it easier to understand. Maybe something like `Use Origin Send Address For Change`

**Comment by 0rtis** [comment]
`Use Origin Send Address For Change` is more confusing since the destination cannot be rolled on to a new tag. When a tagged address is spent, the tag can be ported (rolled) to a change address, but only from the source address to the change address.
